GET http://localhost:8000/api/dams

###
POST http://localhost:8000/api/dams
Content-Type: "application/json"
Accept: "application/json"

{
    "river_name" : "TEST",
    "dam_name":"TEST",
    "long" : "TEST",
    "lat":"TEST",
    "siap" : 0.50,
    "siaga":1,
    "awas":1.20
}

###
GET http://localhost:8000/api/dams/2

###
PUT http://localhost:8000/api/dams/2
Content-Type: "application/json"
Accept: "application/json"

{
    "river_name" : "TEST",
    "dam_name":"TEST UPDATE",
    "long" : "TEST UPDATE",
    "lat":"TEST UPDATE",
    "siap" : 0.50,
    "siaga":1,
    "awas":1.20
}

###
DELETE http://localhost:8000/api/dams/3

### POB CRUD
GET http://localhost:8000/api/pob

###
POST http://localhost:8000/api/pob
Content-Type: "application/json"
Accept: "application/json"

{
    "name" : "POB 2",
    "phone_number":"082222222",
    "dam_id" : 1
}

###
GET http://localhost:8000/api/pob/2

###
PUT http://localhost:8000/api/pob/2
Content-Type: "application/json"
Accept: "application/json"

{
    "name" : "POB 2 update",
    "phone_number":"082222222",
    "dam_id" : 2
}

###
DELETE http://localhost:8000/api/pob/2


### REPORT CRUD
GET http://localhost:8000/api/reports

###
POST http://localhost:8000/api/reports
Content-Type: "application/json"
Accept: "application/json"

{
    "dam_id" : 2,
    "limpas" : 0.05,
    "debit" : 1800,
    "cuaca" : "mendung",
    "debit_ke_saluran_induk" : 6032,
    "pob_id":1
}

###
GET http://localhost:8000/api/reports/1

###
PUT http://localhost:8000/api/reports/1
Content-Type: "application/json"
Accept: "application/json"

{
    "dam_id" : 2,
    "limpas" : 0.1,
    "debit" : 1800,
    "cuaca" : "terang",
    "debit_ke_saluran_induk" : 6032,
    "pob_id":1
}

###
DELETE http://localhost:8000/api/reports/2
